import { NextResponse } from 'next/server';
import type { RoadmapSuggestion } from '@/lib/types';

/**
 * POST /api/scan
 * Scans JIRA, Confluence, and Slack for new roadmap suggestions.
 *
 * In production this would call the actual APIs. For the prototype,
 * we return real items discovered from the latest scan of GDCU JIRA,
 * Confluence pages, and Slack messages.
 */
export async function POST() {
  try {
    const now = new Date().toISOString();

    // Real items from JIRA, Confluence and Slack — scanned 2026-03-27
    const suggestions: RoadmapSuggestion[] = [
      {
        id: `sug-jira-${Date.now()}-8794`,
        title: 'GDC Free to Play App',
        description: 'New epic for a Free to Play mobile app. Covers the full scope of building a dedicated F2P experience for GDC users — this is a significant new product initiative.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8794',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8794',
          jiraStatus: 'Backlog',
          jiraAssignee: 'Unassigned',
          jiraPriority: 'Medium',
        },
        suggestedPriority: 'p1',
        suggestedType: 'project',
        suggestedGroupId: '',
        relevanceScore: 92,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['epic', 'free-to-play', 'mobile', 'new-product'],
      },
      {
        id: `sug-jira-${Date.now()}-8789`,
        title: 'ACE AI - Embedded Betslips',
        description: 'Development task to embed betslips directly within the Ace AI assistant. High priority — enables users to place bets without leaving the AI conversation flow.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8789',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8789',
          jiraStatus: 'Backlog',
          jiraPriority: 'High',
          jiraAssignee: 'Unassigned',
        },
        suggestedPriority: 'p1',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 88,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['ace-ai', 'betslip', 'high-priority'],
      },
      {
        id: `sug-jira-${Date.now()}-8791`,
        title: 'Ace AI - Embedded Betslip Design',
        description: 'UX/UI design task for the embedded betslip experience within Ace AI. Companion to the development ticket GDCU-8789.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8791',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8791',
          jiraStatus: 'Backlog',
          jiraPriority: 'Medium',
          jiraAssignee: 'Unassigned',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 82,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['ace-ai', 'betslip', 'ux-design'],
      },
      {
        id: `sug-jira-${Date.now()}-8797`,
        title: 'Investigate Performance Improvements for Global News Pagination',
        description: 'Performance investigation for the global news pagination system. Could impact page load times and SEO rankings across all news pages.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8797',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8797',
          jiraStatus: 'Backlog',
          jiraPriority: 'Medium',
          jiraAssignee: 'Unassigned',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 75,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['performance', 'news', 'seo'],
      },
      {
        id: `sug-jira-${Date.now()}-8782`,
        title: 'Add Prediction Filter on US State Homepages',
        description: 'High priority — add prediction filtering capability to US state homepage templates. Allows users to filter by prediction type on state-level landing pages.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8782',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8782',
          jiraStatus: 'Backlog',
          jiraPriority: 'High',
          jiraAssignee: 'Unassigned',
        },
        suggestedPriority: 'p1',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 80,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['predictions', 'us-market', 'high-priority'],
      },
      {
        id: `sug-jira-${Date.now()}-8779`,
        title: 'Add Security Response Headers via Cloudflare Transform Rules',
        description: 'High priority security improvement — implement security response headers (CSP, X-Frame-Options, etc.) using Cloudflare Transform Rules.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8779',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8779',
          jiraStatus: 'Backlog',
          jiraPriority: 'High',
          jiraAssignee: 'Unassigned',
        },
        suggestedPriority: 'p1',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 78,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['security', 'cloudflare', 'high-priority'],
      },
      {
        id: `sug-jira-${Date.now()}-8741`,
        title: 'Create Bloomreach Oplist JSON Endpoint',
        description: 'Multi-site endpoint that outputs an operator list in JSON format for Bloomreach integration. High priority, currently in progress.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8741',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8741',
          jiraStatus: 'In Progress',
          jiraPriority: 'High',
          jiraAssignee: 'Kelvin Yee',
        },
        suggestedPriority: 'p1',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 76,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['bloomreach', 'integration', 'api'],
      },
      {
        id: `sug-jira-${Date.now()}-8800`,
        title: 'Component Creation - Experts Carousel',
        description: 'UX/UI task for creating a new Experts Carousel component. Would showcase expert picks and recommendations.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8800',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8800',
          jiraStatus: 'Backlog',
          jiraPriority: 'Medium',
          jiraAssignee: 'Unassigned',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 70,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['component', 'ux', 'carousel'],
      },
      {
        id: `sug-jira-${Date.now()}-8780`,
        title: 'Ace AI - Improved Prompts',
        description: 'Enhance the AI prompts used by Ace Assistant to improve response quality and relevance for betting recommendations.',
        source: {
          type: 'jira',
          jiraKey: 'GDCU-8780',
          jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8780',
          jiraStatus: 'Backlog',
          jiraPriority: 'Medium',
          jiraAssignee: 'Unassigned',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 72,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['ace-ai', 'prompts', 'ai'],
      },
      {
        id: `sug-confluence-${Date.now()}-betfinder`,
        title: 'BetFinder Partner Integration Guide',
        description: 'New Confluence documentation on how to embed BetFinder into partner websites using WordPress Chat Widget and Cloudflare Worker routes. Indicates active partner rollout.',
        source: {
          type: 'confluence',
          confluencePageId: '6581584502',
          confluenceUrl: 'https://gdcgroup.atlassian.net/wiki/spaces/PT/pages/6581584502/How+to+add+BetFinder+to+a+partner+website',
          confluenceSpaceKey: 'PT',
          confluenceAuthor: 'Mykyta Zadorozhnyi',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 74,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['betfinder', 'partner', 'integration'],
      },
      {
        id: `sug-confluence-${Date.now()}-bizdev`,
        title: 'Business Development Pipeline - Claude Demo App',
        description: 'Commercial team has built a Claude Code demo app for the business development pipeline. Currently running locally, needs hosting and integration with internal data sources (leads, partners, revenue).',
        source: {
          type: 'confluence',
          confluencePageId: '6581813609',
          confluenceUrl: 'https://gdcgroup.atlassian.net/wiki/spaces/AMT/pages/6581813609/Business+Development+Pipeline+-+Claude+Demo+App+v.0.1',
          confluenceSpaceKey: 'AMT',
          confluenceAuthor: 'Gilbert Micallef',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 68,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['claude', 'demo', 'business-development'],
      },
      {
        id: `sug-slack-${Date.now()}-strategy`,
        title: 'Strategy Hub Categorisation Dropdown',
        description: 'Discussion between Mike Pett, Milan, and Pernilla about building a dedicated dropdown for strategy hub categorisation instead of using the general product features field. Start with Texas Hold\'em and Tournament Strategy, make it admin-configurable. Same pattern for casino and betting guide sections.',
        source: {
          type: 'slack',
          slackChannelName: 'Group DM',
          slackMessageUrl: 'https://gdcgroup.slack.com/archives/C0AMZ781Y04/p1774022228363379',
          slackAuthor: 'Mike Pett',
          slackSnippet: 'Use a dedicated dropdown for strategy hub categorisation... Make it admin-configurable so we can add new values without needing a code change.',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 85,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['strategy-hub', 'categorisation', 'admin-config'],
      },
      {
        id: `sug-slack-${Date.now()}-copilot`,
        title: 'Copilot Reskin for New Screen Consistency',
        description: 'Rohan reported that the Copilot touch-up to match the new screen design is currently in dev. No new features — just a reskin for consistency and lots of refactoring/simplification to allow faster building as part of new initiatives.',
        source: {
          type: 'slack',
          slackChannelName: '#sds-optic-eng',
          slackMessageUrl: 'https://gdcgroup.slack.com/archives/C0AKYKP96BX/p1774468730540489',
          slackAuthor: 'Rohan Challa',
          slackSnippet: 'Copilot touch up to match new screen is in dev now... lots of refactoring / simplification to allow us to build quicker as part of the new initiatives',
        },
        suggestedPriority: 'p2',
        suggestedType: 'task',
        suggestedGroupId: '',
        relevanceScore: 65,
        duplicateOfId: null,
        duplicateConfidence: 0,
        status: 'pending',
        deferredUntil: null,
        reviewedAt: null,
        scannedAt: now,
        createdAt: now,
        tags: ['copilot', 'reskin', 'refactoring'],
      },
    ];

    return NextResponse.json({
      ok: true,
      message: `Scan complete. ${suggestions.length} items found across JIRA, Confluence, and Slack.`,
      requestedAt: now,
      suggestions,
      summary: {
        jira: suggestions.filter(s => s.source.type === 'jira').length,
        confluence: suggestions.filter(s => s.source.type === 'confluence').length,
        slack: suggestions.filter(s => s.source.type === 'slack').length,
        total: suggestions.length,
      },
    });
  } catch {
    return NextResponse.json(
      { ok: false, message: 'Failed to complete scan' },
      { status: 500 }
    );
  }
}
