import type { RoadmapItem } from '~/types'

export const mockJiraItems: RoadmapItem[] = [
  {
    key: 'GDCU-8721',
    title: 'Implement operator deeplink tracking pixel',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Sarah',
    ticketType: 'dev',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8721',
  },
  {
    key: 'GDCU-8690',
    title: 'Redesign comparison table component',
    status: 'To Do',
    priority: 'High',
    assignee: 'Tom',
    ticketType: 'design',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8690',
  },
  {
    key: 'GDCU-8645',
    title: 'Fix breadcrumb schema markup on state pages',
    status: 'In QA',
    priority: 'Medium',
    assignee: 'James',
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8645',
  },
  {
    key: 'GDCU-8612',
    title: 'Build new bonus calculator widget',
    status: 'Backlog',
    priority: 'Medium',
    assignee: null,
    ticketType: 'both',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8612',
  },
  {
    key: 'GDCU-8598',
    title: 'Add sort dropdown to operator list page',
    status: 'To Do',
    priority: 'Medium',
    assignee: 'Sarah',
    ticketType: 'dev',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8598',
  },
  {
    key: 'GDCU-8567',
    title: 'Migrate legacy review pages to new template',
    status: 'Backlog',
    priority: 'Low',
    assignee: null,
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8567',
  },
  {
    key: 'GDCU-8543',
    title: 'Design mobile-first casino cards',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Tom',
    ticketType: 'design',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8543',
  },
  {
    key: 'GDCU-8510',
    title: 'Implement A/B test framework for CTAs',
    status: 'Backlog',
    priority: 'High',
    assignee: 'James',
    ticketType: 'dev',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8510',
  },
  {
    key: 'GDCU-8489',
    title: 'Fix mobile nav drawer z-index stacking issue',
    status: 'To Do',
    priority: 'Medium',
    assignee: 'Sarah',
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8489',
  },
  {
    key: 'GDCU-8456',
    title: 'Add user rating system to operator reviews',
    status: 'Backlog',
    priority: 'Medium',
    assignee: null,
    ticketType: 'both',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8456',
  },
  {
    key: 'GDCU-8423',
    title: 'Redesign state page hero sections',
    status: 'Backlog',
    priority: 'Low',
    assignee: 'Tom',
    ticketType: 'design',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8423',
  },
  {
    key: 'GDCU-8401',
    title: 'Optimize image loading pipeline',
    status: 'Backlog',
    priority: 'Medium',
    assignee: 'James',
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8401',
  },
  {
    key: 'GDCU-8378',
    title: 'Build new responsible gambling interstitial',
    status: 'To Do',
    priority: 'High',
    assignee: null,
    ticketType: 'both',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8378',
  },
  {
    key: 'GDCU-8355',
    title: 'Add lazy loading to below-fold content blocks',
    status: 'Backlog',
    priority: 'Low',
    assignee: null,
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8355',
  },
  {
    key: 'GDCU-8334',
    title: 'Implement push notification opt-in flow',
    status: 'Backlog',
    priority: 'Low',
    assignee: null,
    ticketType: 'both',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8334',
  },
  {
    key: 'GDCU-8312',
    title: 'CRO: Improve above-fold CTA placement on review pages',
    status: 'To Do',
    priority: 'High',
    assignee: 'Tom',
    ticketType: 'design',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8312',
  },
  {
    key: 'GDCU-8290',
    title: 'Fix duplicate meta descriptions on paginated pages',
    status: 'To Do',
    priority: 'Medium',
    assignee: 'James',
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'jira',
    jiraUrl: 'https://gdcgroup.atlassian.net/browse/GDCU-8290',
  },
]

export const mockAuditItems: RoadmapItem[] = [
  {
    key: 'AUDIT-01',
    title: 'Add filter controls to operator comparison tables',
    status: 'New',
    priority: 'High',
    assignee: null,
    ticketType: 'both',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P1',
    auditEffort: 'Medium',
    auditArea: 'Filtering',
  },
  {
    key: 'AUDIT-02',
    title: 'Redesign casino card layout for mobile viewports',
    status: 'New',
    priority: 'High',
    assignee: null,
    ticketType: 'design',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P0',
    auditEffort: 'High',
    auditArea: 'Card Design',
  },
  {
    key: 'AUDIT-03',
    title: 'Implement sticky CTA bar on long review pages',
    status: 'New',
    priority: 'Medium',
    assignee: null,
    ticketType: 'dev',
    lane: 'Improvements',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P1',
    auditEffort: 'Low',
    auditArea: 'CRO',
  },
  {
    key: 'AUDIT-04',
    title: 'Add structured data markup to all FAQ sections',
    status: 'New',
    priority: 'Medium',
    assignee: null,
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P2',
    auditEffort: 'Low',
    auditArea: 'SEO',
  },
  {
    key: 'AUDIT-05',
    title: 'Build interactive odds comparison tool',
    status: 'New',
    priority: 'Medium',
    assignee: null,
    ticketType: 'both',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P1',
    auditEffort: 'High',
    auditArea: 'New Feature',
  },
  {
    key: 'AUDIT-06',
    title: 'Fix Core Web Vitals LCP issues on landing pages',
    status: 'New',
    priority: 'High',
    assignee: null,
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P0',
    auditEffort: 'Medium',
    auditArea: 'Performance',
  },
  {
    key: 'AUDIT-07',
    title: 'Add geo-targeted bonus display logic',
    status: 'New',
    priority: 'Low',
    assignee: null,
    ticketType: 'dev',
    lane: 'New Product Features',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P2',
    auditEffort: 'Medium',
    auditArea: 'Personalisation',
  },
  {
    key: 'AUDIT-08',
    title: 'Consolidate duplicate category pages for SEO',
    status: 'New',
    priority: 'Low',
    assignee: null,
    ticketType: 'dev',
    lane: 'Site Hygiene',
    weekIdx: -1,
    note: '',
    source: 'audit',
    auditPriority: 'P3',
    auditEffort: 'Low',
    auditArea: 'SEO',
  },
]
