import type { RoadmapItem, SourceReference } from '~/types'

// ── Mock project data for gambling.com product roadmap planner ────────

export const mockProjects: RoadmapItem[] = [
  // ───────────────────────────────────────────────────────────────────
  // EPICS (multi-week)
  // ───────────────────────────────────────────────────────────────────
  {
    key: 'PROJ-001',
    title: 'Casino Reviews Page Redesign',
    description: 'Full redesign of the casino reviews landing page with updated card layout, filtering, and improved mobile experience.',
    status: 'confirmed',
    priority: 'High',
    assignee: 'Sarah',
    lane: 'New Product Features',
    projectSize: 'epic',
    durationWeeks: 3,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 8,
    confidence: 0.92,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'slack',
        id: 'C04PRODUCT',
        title: '#product',
        url: 'https://gdcgroup.slack.com/archives/C04PRODUCT/p1709812345',
        excerpt: 'We need to get the casino reviews redesign shipped before end of Q1. The current page has a 68% bounce rate on mobile — the new card layout from Tom should fix that.',
        timestamp: '2026-03-06T10:25:00Z',
      },
      {
        type: 'confluence',
        id: '294817',
        title: 'Casino Reviews Redesign Spec',
        url: 'https://gdcgroup.atlassian.net/wiki/spaces/PROD/pages/294817',
        excerpt: 'The proposed redesign includes a filterable grid of operator cards, sticky comparison bar, and revamped trust signals section. Target: 15% uplift in CTR to operator pages.',
        timestamp: '2026-03-04T14:00:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-002',
    title: 'Operator Comparison Tool',
    description: 'Interactive side-by-side comparison tool allowing users to compare up to 3 operators on bonuses, odds, features, and trust scores.',
    status: 'proposed',
    priority: 'High',
    assignee: 'Tom',
    lane: 'New Product Features',
    projectSize: 'epic',
    durationWeeks: 4,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 13,
    confidence: 0.85,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'confluence',
        id: '301245',
        title: 'Q1 2026 Product Roadmap',
        url: 'https://gdcgroup.atlassian.net/wiki/spaces/PROD/pages/301245',
        excerpt: 'Operator comparison tool is the #1 priority for Q2. User research shows 42% of visitors want to compare operators before signing up. Competitor analysis: Oddschecker and AskGamblers both have this.',
        timestamp: '2026-03-01T09:30:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-003',
    title: 'Mobile Betting Experience Overhaul',
    description: 'Rework the mobile betting pages with bottom-sheet navigation, swipeable cards, and optimised touch targets for bet placement.',
    status: 'proposed',
    priority: 'Medium',
    assignee: 'James',
    lane: 'Improvements',
    projectSize: 'epic',
    durationWeeks: 3,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 8,
    confidence: 0.65,
    confidenceLevel: 'medium',
    sources: [
      {
        type: 'slack',
        id: 'C04MOBILE',
        title: '#mobile-team',
        url: 'https://gdcgroup.slack.com/archives/C04MOBILE/p1710234567',
        excerpt: 'Mobile conversion is 40% lower than desktop on betting pages. We should overhaul the whole experience — the current layout wastes too much vertical space and the CTA buttons are too small on smaller screens.',
        timestamp: '2026-03-12T11:15:00Z',
      },
      {
        type: 'slack',
        id: 'C04MOBILE',
        title: '#mobile-team',
        url: 'https://gdcgroup.slack.com/archives/C04MOBILE/p1710298765',
        excerpt: 'Agreed. I\'ve been looking at how Sky Bet and Paddy Power handle their mobile betslips — the bottom sheet pattern works really well. Let me put together some wireframes.',
        timestamp: '2026-03-13T09:45:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-004',
    title: 'SEO Schema Markup Migration',
    description: 'Migrate all pages from legacy microdata to JSON-LD structured data, adding FAQ, Review, and Breadcrumb schema across the site.',
    status: 'confirmed',
    priority: 'High',
    assignee: 'James',
    lane: 'Site Hygiene',
    projectSize: 'epic',
    durationWeeks: 2,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 5,
    confidence: 0.88,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'confluence',
        id: '305612',
        title: 'SEO Schema Migration Plan',
        url: 'https://gdcgroup.atlassian.net/wiki/spaces/SEO/pages/305612',
        excerpt: 'Current microdata implementation is outdated and causing validation errors in Search Console. Migration to JSON-LD will resolve 347 existing warnings and enable rich result eligibility for review pages.',
        timestamp: '2026-03-08T16:20:00Z',
      },
      {
        type: 'jira',
        id: 'GDCU-9102',
        title: 'GDCU-9102: Migrate structured data to JSON-LD',
        url: 'https://gdcgroup.atlassian.net/browse/GDCU-9102',
        excerpt: 'Epic ticket covering schema migration across all page templates. Subtasks created for casino pages, betting pages, review pages, and state/market pages.',
        timestamp: '2026-03-09T10:00:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-005',
    title: 'User Account Dashboard',
    description: 'New authenticated user dashboard with saved operators, personalised recommendations, betting history, and notification preferences.',
    status: 'proposed',
    priority: 'Medium',
    assignee: null,
    lane: 'New Product Features',
    projectSize: 'epic',
    durationWeeks: 4,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 13,
    confidence: 0.55,
    confidenceLevel: 'medium',
    sources: [
      {
        type: 'slack',
        id: 'C04STRATEGY',
        title: '#strategy',
        url: 'https://gdcgroup.slack.com/archives/C04STRATEGY/p1710456789',
        excerpt: 'We should build a proper user dashboard. Right now logged-in users get nothing extra — there\'s no reason to create an account. If we add saved operators and personalised recs we could drive repeat visits by 25%+.',
        timestamp: '2026-03-15T14:30:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-006',
    title: 'Responsible Gambling Hub',
    description: 'Dedicated responsible gambling resource centre with self-assessment tools, deposit limit calculators, and links to support organisations.',
    status: 'confirmed',
    priority: 'High',
    assignee: 'Sarah',
    lane: 'New Product Features',
    projectSize: 'epic',
    durationWeeks: 3,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 8,
    confidence: 0.82,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'confluence',
        id: '308901',
        title: 'Responsible Gambling Hub — Product Brief',
        url: 'https://gdcgroup.atlassian.net/wiki/spaces/PROD/pages/308901',
        excerpt: 'Regulatory requirements in UK and Ontario markets require a more prominent responsible gambling presence. The hub will include self-assessment quiz, session time calculator, and curated links to GamCare, Gordon Moody, and Gamblers Anonymous.',
        timestamp: '2026-03-10T11:00:00Z',
      },
      {
        type: 'slack',
        id: 'C04PRODUCT',
        title: '#product',
        url: 'https://gdcgroup.slack.com/archives/C04PRODUCT/p1710345678',
        excerpt: 'Compliance team flagged this as urgent — new UKGC guidance means we need a dedicated RG hub, not just footer links. Let\'s prioritise this for Q2 kickoff.',
        timestamp: '2026-03-13T16:10:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },

  // ───────────────────────────────────────────────────────────────────
  // DELIVERABLES (single-week)
  // ───────────────────────────────────────────────────────────────────
  {
    key: 'PROJ-007',
    title: 'Add Odds Comparison Widget',
    description: 'Embed a lightweight odds comparison widget on betting event pages showing live odds from top 5 operators.',
    status: 'confirmed',
    priority: 'High',
    assignee: 'Tom',
    lane: 'New Product Features',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 3,
    confidence: 0.9,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'slack',
        id: 'C04PRODUCT',
        title: '#product',
        url: 'https://gdcgroup.slack.com/archives/C04PRODUCT/p1710123456',
        excerpt: 'The odds widget is ready to go — API integration is done, we just need the frontend component. Tom has the designs finalised. Should be a quick one-week delivery.',
        timestamp: '2026-03-11T09:20:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-008',
    title: 'Fix CLS Issues on Homepage',
    description: 'Resolve cumulative layout shift caused by late-loading operator logos and dynamic banner heights on the homepage.',
    status: 'in-progress',
    priority: 'High',
    assignee: 'James',
    lane: 'Site Hygiene',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 2,
    confidence: 0.95,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'slack',
        id: 'C04DEV',
        title: '#dev',
        url: 'https://gdcgroup.slack.com/archives/C04DEV/p1710567890',
        excerpt: 'CLS on homepage spiked to 0.18 after last deploy — the operator logo carousel and the promo banner are both shifting content. I\'ve identified the root cause, working on explicit dimension reservations now.',
        timestamp: '2026-03-16T08:40:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-009',
    title: 'Update Responsible Gambling Footer',
    description: 'Add new GamStop and IBAS logos to the site footer and update responsible gambling copy to meet latest UKGC guidelines.',
    status: 'confirmed',
    priority: 'Medium',
    assignee: 'Sarah',
    lane: 'Site Hygiene',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 1,
    confidence: 0.93,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'confluence',
        id: '310234',
        title: 'UKGC Footer Compliance Update',
        url: 'https://gdcgroup.atlassian.net/wiki/spaces/LEGAL/pages/310234',
        excerpt: 'As of March 2026, UKGC requires affiliate sites to display GamStop and IBAS logos alongside existing responsible gambling badges. Footer copy must also reference the National Gambling Helpline number.',
        timestamp: '2026-03-07T13:45:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-010',
    title: 'A/B Test New CTA Colors',
    description: 'Run a multivariate test on primary CTA buttons comparing current blue against green and orange variants across operator review pages.',
    status: 'proposed',
    priority: 'Medium',
    assignee: 'Tom',
    lane: 'Improvements',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 2,
    confidence: 0.6,
    confidenceLevel: 'medium',
    sources: [
      {
        type: 'slack',
        id: 'C04CRO',
        title: '#cro',
        url: 'https://gdcgroup.slack.com/archives/C04CRO/p1710654321',
        excerpt: 'We should test different CTA colours on the review pages. The blue blends in too much with the content — competitors like Bonus Finder use high-contrast green CTAs and their reported CTR is significantly higher.',
        timestamp: '2026-03-17T10:05:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-011',
    title: 'Implement Lazy Loading for Operator Logos',
    description: 'Add native lazy loading and LQIP placeholders for operator logo images across all listing and comparison pages.',
    status: 'proposed',
    priority: 'Low',
    assignee: null,
    lane: 'Site Hygiene',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 2,
    confidence: 0.4,
    confidenceLevel: 'low',
    sources: [
      {
        type: 'slack',
        id: 'C04DEV',
        title: '#dev',
        url: 'https://gdcgroup.slack.com/archives/C04DEV/p1710198765',
        excerpt: 'Noticed we\'re loading 40+ operator logos eagerly on the comparison pages. Should probably add lazy loading — it\'d shave a good 200-300ms off LCP on those pages.',
        timestamp: '2026-03-11T15:50:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-012',
    title: 'Add New Market: Ontario Sports Betting',
    description: 'Create Ontario-specific sports betting landing page with localised operator listings, provincial regulations, and CAD bonus amounts.',
    status: 'proposed',
    priority: 'Medium',
    assignee: null,
    lane: 'New Product Features',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 3,
    confidence: 0.7,
    confidenceLevel: 'medium',
    sources: [
      {
        type: 'confluence',
        id: '312456',
        title: 'Ontario Market Expansion Plan',
        url: 'https://gdcgroup.atlassian.net/wiki/spaces/GROWTH/pages/312456',
        excerpt: 'Ontario sports betting market is growing 30% YoY. We have operator partnerships ready with bet365 Canada, FanDuel Ontario, and BetMGM Ontario. Need a dedicated landing page to capture organic search traffic for "Ontario sports betting" queries.',
        timestamp: '2026-03-14T12:30:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-013',
    title: 'Fix Broken Deeplinks on UK Pages',
    description: 'Audit and repair broken operator deeplinks on UK casino and betting pages caused by recent affiliate platform migration.',
    status: 'in-progress',
    priority: 'Blocked',
    assignee: 'James',
    lane: 'Site Hygiene',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 2,
    confidence: 0.95,
    confidenceLevel: 'high',
    sources: [
      {
        type: 'slack',
        id: 'C04BUGS',
        title: '#bugs',
        url: 'https://gdcgroup.slack.com/archives/C04BUGS/p1710712345',
        excerpt: 'Multiple broken deeplinks reported on UK pages since the affiliate platform migration last week. bet365, William Hill, and Ladbrokes links are all 404ing. This is directly hitting revenue — need to fix ASAP.',
        timestamp: '2026-03-18T08:15:00Z',
      },
      {
        type: 'slack',
        id: 'C04BUGS',
        title: '#bugs',
        url: 'https://gdcgroup.slack.com/archives/C04BUGS/p1710756789',
        excerpt: 'Found the issue — the new affiliate platform changed the URL scheme from /redirect/ to /track/. I\'ve got a mapping of old → new URLs but need to update the deeplink service config. Blocked waiting on the new API credentials from the affiliate team.',
        timestamp: '2026-03-18T14:30:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
  {
    key: 'PROJ-014',
    title: 'Revamp Email Signup Flow',
    description: 'Redesign the email newsletter signup with a two-step opt-in, preference selection for casino/betting/both, and welcome sequence trigger.',
    status: 'proposed',
    priority: 'Low',
    assignee: null,
    lane: 'Improvements',
    projectSize: 'deliverable',
    durationWeeks: 1,
    startWeekIdx: -1,
    endWeekIdx: -1,
    effortPoints: 3,
    confidence: 0.45,
    confidenceLevel: 'low',
    sources: [
      {
        type: 'slack',
        id: 'C04STRATEGY',
        title: '#strategy',
        url: 'https://gdcgroup.slack.com/archives/C04STRATEGY/p1710534567',
        excerpt: 'Our email list growth has flatlined. The current single-field signup gets about 0.3% conversion. Would be worth testing a two-step flow with preference selection — lets us segment from day one and send more relevant content.',
        timestamp: '2026-03-16T11:20:00Z',
      },
    ],
    note: '',
    scanId: 'mock-scan-001',
  },
]
